package com.careeragent.domain.enums;
public enum InterviewAgentState { INIT, PREPARING, ANALYZING_JD, ANALYZING_RESUME, BUILDING_STRATEGY, ASKING, WAITING_ANSWER, EVALUATING, DECIDING, REPORTING, FINISHED, CANCELLED, FAILED }
