package com.careeragent.interview.agent;

import com.careeragent.agent.llm.LLMAdapter;import com.careeragent.domain.entity.*;import com.careeragent.domain.enums.*;import java.util.*;import java.util.function.Consumer;import org.springframework.stereotype.Component;

interface InterviewSkill<I,O>{String name();O execute(I input);}
record JdInput(String jobName,String content){}
record JdResult(List<String> technicalStack,List<String> requirements,List<String> interviewFocus){}
record ResumeInput(String content){}
record ResumeResult(List<String> technicalSkills,List<String> projects,List<String> deepDiveDirections,List<String> risks){}
record StrategyInput(JdResult jd,ResumeResult resume,InterviewMode mode,Integer duration){}
record TopicPlan(String topic,String source,int weight,int maxQuestions){}
record StrategyResult(List<TopicPlan> topics,int minimumQuestions,int maximumQuestions){}
record QuestionInput(String topic,int depth,String jd,String resume,List<InterviewMessage> history,String missingPoint){}
record EvaluationResult(int technicalCorrectness,int completeness,int communication,int overallScore,List<String> strengths,List<String> missingPoints,List<String> risks,InterviewDecision recommendation){}
record DecisionResult(InterviewDecision decision,String reason,String nextTopic,int nextDepth,String missingPoint){}
record ReportResult(int score,int technicalScore,int communicationScore,int completenessScore,int jdCoverage,String strength,String weakness,String suggestion){}

@Component class JdUnderstandingSkill implements InterviewSkill<JdInput,JdResult>{public String name(){return "jd_understanding";}public JdResult execute(JdInput in){var text=(in.jobName()+" "+in.content()).toLowerCase();var stack=List.of("JavaScript","TypeScript","React","Vue","Java","Spring Boot","Python","SQL","Redis","Docker","LLM","Agent").stream().filter(v->text.contains(v.toLowerCase())).toList();var requirements=Arrays.stream(Optional.ofNullable(in.content()).orElse("").split("[。；;\n]")).map(String::trim).filter(v->v.length()>4).limit(8).toList();var focus=new ArrayList<String>();focus.addAll(stack);focus.add("项目经历");focus.add("设计权衡");return new JdResult(stack,requirements,focus.stream().distinct().limit(8).toList());}}
@Component class ResumeAnalysisSkill implements InterviewSkill<ResumeInput,ResumeResult>{public String name(){return "resume_analysis";}public ResumeResult execute(ResumeInput in){var text=Optional.ofNullable(in.content()).orElse("");var skills=List.of("JavaScript","TypeScript","React","Vue","Java","Spring Boot","Python","SQL","Redis","Docker","LLM","Agent").stream().filter(text.toLowerCase()::contains).toList();var projects=Arrays.stream(text.split("\n")).map(String::trim).filter(v->v.contains("项目")||v.startsWith("##")||v.startsWith("###")).limit(6).toList();return new ResumeResult(skills,projects,List.of("项目背景与职责","技术方案","设计权衡","底层原理","量化结果与复盘"),List.of("核实个人职责边界","核实量化结果与技术选型依据"));}}
@Component class InterviewStrategySkill implements InterviewSkill<StrategyInput,StrategyResult>{public String name(){return "interview_strategy";}public StrategyResult execute(StrategyInput in){var max=in.duration()<=15?5:in.duration()<=30?8:12;var topics=new ArrayList<TopicPlan>();topics.add(new TopicPlan("项目深挖","RESUME",40,4));for(var topic:in.jd().interviewFocus())if(topics.size()<5&&!"项目经历".equals(topic)&&!"设计权衡".equals(topic))topics.add(new TopicPlan(topic,"JD",15,2));topics.add(new TopicPlan("综合复盘","GENERAL",10,1));return new StrategyResult(topics,Math.min(5,max),max);}}
@Component class AnswerEvaluationSkill implements InterviewSkill<Map<String,Object>,EvaluationResult>{public String name(){return "answer_evaluation";}public EvaluationResult execute(Map<String,Object> in){var answer=Objects.toString(in.get("answer"),"").trim();var question=Objects.toString(in.get("question"),"");var length=answer.length();var hasNumber=answer.matches(".*\\d+.*");var hasReason=answer.matches(".*(因为|所以|为了|考虑|权衡|选择).*" );var hasAction=answer.matches(".*(我负责|我实现|我设计|我主导|我参与|我们).*" );var completeness=Math.min(92,35+length/3+(hasAction?12:0)+(hasNumber?8:0));var communication=Math.min(92,50+Math.min(25,length/6)+(hasReason?10:0));var technical=Math.min(92,40+Math.min(30,length/5)+(hasReason?10:0));var missing=new ArrayList<String>();if(length<80)missing.add("请补充更具体的背景、个人行动和结果");if(!hasAction)missing.add("请说明你个人具体负责的模块和贡献");if(!hasNumber)missing.add("请补充项目规模或可验证的量化结果");if(question.contains("自我介绍")&&length<120)missing.add("请补充求职方向和与岗位最相关的经历");var overall=(technical*45+completeness*35+communication*20)/100;var strengths=answer.isBlank()?List.<String>of():List.of("回答与当前问题相关");return new EvaluationResult(technical,completeness,communication,overall,strengths,missing,List.of(),overall<75?InterviewDecision.FOLLOW_UP:InterviewDecision.NEXT_TOPIC);}}
@Component class FollowUpSkill implements InterviewSkill<Map<String,Object>,DecisionResult>{public String name(){return "follow_up";}public DecisionResult execute(Map<String,Object> in){var evaluation=(EvaluationResult)in.get("evaluation");var followUps=(Integer)in.getOrDefault("followUps",0);var turn=(Integer)in.getOrDefault("turn",0);var minimum=(Integer)in.getOrDefault("minimumQuestions",5);var max=(Integer)in.getOrDefault("maxQuestions",8);var depth=(Integer)in.getOrDefault("currentDepth",1);var topic=Objects.toString(in.get("topic"));var nextTopic=(String)in.get("nextTopic");if(turn>=max)return new DecisionResult(InterviewDecision.FINISH,"已达到问题预算",null,0,null);if("项目深挖".equals(topic)&&depth<4){var missing=evaluation.missingPoints().isEmpty()?null:evaluation.missingPoints().get(0);return new DecisionResult(InterviewDecision.FOLLOW_UP,"项目深挖尚未完成",topic,depth+1,missing);}if(evaluation.recommendation()==InterviewDecision.FOLLOW_UP&&followUps<3){var missing=evaluation.missingPoints().isEmpty()?null:evaluation.missingPoints().get(0);return new DecisionResult(InterviewDecision.FOLLOW_UP,"当前回答仍有关键证据缺失",topic,depth+1,missing);}if(nextTopic==null){if(turn>=minimum)return new DecisionResult(InterviewDecision.FINISH,"面试计划已完成",null,0,null);return new DecisionResult(InterviewDecision.FOLLOW_UP,"继续深挖最后一个主题",topic,depth+1,null);}return new DecisionResult(InterviewDecision.NEXT_TOPIC,"当前主题已获得足够信息",nextTopic,1,null);}}
@Component class ProjectDeepDiveSkill{String instruction(int depth){return switch(Math.min(depth,5)){case 1->"询问项目背景、规模和候选人职责";case 2->"追问技术方案与具体实现";case 3->"追问设计权衡、替代方案和选择依据";case 4->"追问底层原理、边界条件与故障处理";default->"追问量化结果、复盘和改进方案";};}}
@Component class InterviewerSkill{private final LLMAdapter llm;private final ProjectDeepDiveSkill deepDive;InterviewerSkill(LLMAdapter llm,ProjectDeepDiveSkill deepDive){this.llm=llm;this.deepDive=deepDive;}String stream(QuestionInput in,String model,Consumer<String> sink){var prompt="你是严格、专业的技术面试官。每次只提出一个问题，不给答案。问题必须基于 JD、选定简历、当前主题和已经回答的内容，禁止随机出题或重复问题。"+deepDive.instruction(in.depth());var input=Map.of("topic",in.topic(),"depth",in.depth(),"jd",in.jd(),"resume",in.resume(),"recentHistory",in.history().stream().skip(Math.max(0,in.history().size()-8)).map(m->Map.of("role",m.getRole(),"content",m.getContent())).toList(),"missingPoint",Objects.toString(in.missingPoint(),""));var generated=llm.textStream(prompt,input,model,text->{});if(valid(generated,in.history())){sink.accept(generated);return generated;}var fallback=fallback(in);sink.accept(fallback);return fallback;}private boolean valid(String value,List<InterviewMessage> history){if(value==null||value.isBlank())return false;var normalized=normalize(value);return history.stream().filter(m->"assistant".equals(m.getRole())).map(InterviewMessage::getContent).filter(Objects::nonNull).map(this::normalize).noneMatch(old->old.equals(normalized)||similar(old,normalized));}private boolean similar(String a,String b){if(a.length()<12||b.length()<12)return false;var shorter=a.length()<=b.length()?a:b;var longer=a.length()>b.length()?a:b;return longer.contains(shorter)||commonPrefix(a,b)>=Math.min(a.length(),b.length())*.7;}private int commonPrefix(String a,String b){int n=Math.min(a.length(),b.length()),i=0;while(i<n&&a.charAt(i)==b.charAt(i))i++;return i;}private String normalize(String value){return value.replaceAll("[\\s，。？！、,:;]","");}private String fallback(QuestionInput in){if(in.missingPoint()!=null&&!in.missingPoint().isBlank())return "结合你刚才的回答，"+in.missingPoint()+"？";var lastAnswer=in.history().stream().filter(m->"user".equals(m.getRole())).reduce((a,b)->b).map(InterviewMessage::getContent).orElse("你刚才的回答");var context=lastAnswer.length()>45?lastAnswer.substring(0,45)+"…":lastAnswer;return switch(Math.min(in.depth(),5)){case 1->"请介绍这个项目的背景、团队分工，以及你个人负责的部分。";case 2->"你刚才提到“"+context+"”，请具体说明你负责模块的技术方案和实现过程。";case 3->"在这个方案中你比较过哪些替代方案，最后基于什么权衡做出选择？";case 4->"请进一步说明这个方案的底层原理、边界条件和故障处理方式。";default->"这个项目最终取得了什么可量化的结果，如果重做你会如何改进？";};}}
@Component class ReportSkill implements InterviewSkill<List<InterviewEvaluation>,ReportResult>{public String name(){return "report";}public ReportResult execute(List<InterviewEvaluation> values){if(values.isEmpty())return new ReportResult(0,0,0,0,0,"有效回答不足","尚未完成有效问答","完成至少一轮面试问答");var score=(int)values.stream().mapToInt(InterviewEvaluation::getOverallScore).average().orElse(0);var tech=(int)values.stream().mapToInt(InterviewEvaluation::getTechnicalCorrectness).average().orElse(0);var complete=(int)values.stream().mapToInt(InterviewEvaluation::getCompleteness).average().orElse(0);var comm=(int)values.stream().mapToInt(InterviewEvaluation::getCommunication).average().orElse(0);var strengths=values.stream().flatMap(v->v.getStrengths().stream()).distinct().limit(3).toList();var weak=values.stream().flatMap(v->v.getMissingPoints().stream()).distinct().limit(4).toList();return new ReportResult(score,tech,comm,complete,Math.min(100,values.size()*20),String.join("；",strengths),String.join("；",weak),"围绕薄弱点补充真实项目证据，并使用背景、行动、权衡、结果的结构重新回答");}}
