package com.careeragent.interview.agent;

import com.baomidou.mybatisplus.core.toolkit.Wrappers;import com.careeragent.domain.entity.*;import com.careeragent.domain.enums.*;import com.careeragent.mapper.*;import com.fasterxml.jackson.databind.ObjectMapper;import java.util.*;import java.util.function.Consumer;import lombok.RequiredArgsConstructor;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;

@Service @RequiredArgsConstructor
public class InterviewAgentOrchestrator {
 private final JdUnderstandingSkill jdSkill;private final ResumeAnalysisSkill resumeSkill;private final InterviewStrategySkill strategySkill;private final InterviewerSkill interviewerSkill;private final AnswerEvaluationSkill evaluationSkill;private final FollowUpSkill followUpSkill;private final ReportSkill reportSkill;private final InterviewMemoryManager memoryManager;private final InterviewSessionMapper sessionMapper;private final InterviewMessageMapper messageMapper;private final InterviewEvaluationMapper evaluationMapper;private final InterviewReportMapper reportMapper;private final ObjectMapper mapper;

 @Transactional public String prepare(InterviewSession session,String jobName,String jd,String resume,Consumer<String> sink){transition(session,InterviewAgentState.PREPARING);session.setJdSnapshot(jd);session.setResumeSnapshot(resume);transition(session,InterviewAgentState.ANALYZING_JD);var jdResult=jdSkill.execute(new JdInput(jobName,jd));session.setJdAnalysis(mapper.convertValue(jdResult,Map.class));transition(session,InterviewAgentState.ANALYZING_RESUME);var resumeResult=resumeSkill.execute(new ResumeInput(resume));session.setResumeAnalysis(mapper.convertValue(resumeResult,Map.class));memoryManager.rememberProfile(session.getUserId(),jobName,resumeResult);transition(session,InterviewAgentState.BUILDING_STRATEGY);var strategy=strategySkill.execute(new StrategyInput(jdResult,resumeResult,session.getMode(),session.getDuration()));session.setInterviewStrategy(mapper.convertValue(strategy,Map.class));session.setCurrentTopic("自我介绍");session.setCurrentDepth(1);session.setCurrentTurn(0);session.setSessionMemory(new LinkedHashMap<>(Map.of("askedTopics",new ArrayList<>(),"weaknesses",new ArrayList<>(),"strengths",new ArrayList<>(),"followUpCount",0)));transition(session,InterviewAgentState.ASKING);var question="你好，欢迎参加本次模拟面试。请先做一个 1–2 分钟的自我介绍，重点说明你的求职方向、核心技能和与本岗位最相关的项目经历。";sink.accept(question);transition(session,InterviewAgentState.WAITING_ANSWER);return question;}

 @Transactional public AgentTurnResult answer(InterviewSession session,InterviewMessage question,InterviewMessage answer,List<InterviewMessage> history,Consumer<String> sink){if(session.getAgentState()!=InterviewAgentState.WAITING_ANSWER)throw new IllegalStateException("当前状态不能接收回答："+session.getAgentState());transition(session,InterviewAgentState.EVALUATING);var evaluation=evaluationSkill.execute(Map.of("question",question.getContent(),"answer",answer.getContent(),"topic",session.getCurrentTopic()));transition(session,InterviewAgentState.DECIDING);var strategy=mapper.convertValue(session.getInterviewStrategy(),StrategyResult.class);var memory=new LinkedHashMap<>(Optional.ofNullable(session.getSessionMemory()).orElse(Map.of()));var followUps=((Number)memory.getOrDefault("followUpCount",0)).intValue();var nextTopic=nextTopic(strategy,session.getCurrentTopic());var decisionInput=new HashMap<String,Object>();decisionInput.put("evaluation",evaluation);decisionInput.put("followUps",followUps);decisionInput.put("turn",session.getCurrentTurn()+1);decisionInput.put("minimumQuestions",strategy.minimumQuestions());decisionInput.put("maxQuestions",strategy.maximumQuestions());decisionInput.put("topic",session.getCurrentTopic());decisionInput.put("currentDepth",session.getCurrentDepth());decisionInput.put("nextTopic",nextTopic);var decision=followUpSkill.execute(decisionInput);
  var entity=new InterviewEvaluation();entity.setSessionId(session.getId());entity.setTurnNumber(session.getCurrentTurn()+1);entity.setQuestionMessageId(question.getId());entity.setAnswerMessageId(answer.getId());entity.setTopic(session.getCurrentTopic());entity.setTechnicalCorrectness(evaluation.technicalCorrectness());entity.setCompleteness(evaluation.completeness());entity.setCommunication(evaluation.communication());entity.setOverallScore(evaluation.overallScore());entity.setStrengths(evaluation.strengths());entity.setMissingPoints(evaluation.missingPoints());entity.setRiskPoints(evaluation.risks());entity.setRecommendedDecision(evaluation.recommendation());entity.setFinalDecision(decision.decision());entity.setDecisionReason(decision.reason());evaluationMapper.insert(entity);
  session.setCurrentTurn(session.getCurrentTurn()+1);session.setDecision(decision.decision());append(memory,"strengths",evaluation.strengths());append(memory,"weaknesses",evaluation.missingPoints());memory.put("followUpCount",decision.decision()==InterviewDecision.FOLLOW_UP?followUps+1:0);session.setSessionMemory(memory);
  if(decision.decision()==InterviewDecision.FINISH){transition(session,InterviewAgentState.REPORTING);return new AgentTurnResult(decision.decision(),null,entity);}
  session.setCurrentTopic(decision.nextTopic());session.setCurrentDepth(decision.nextDepth());transition(session,InterviewAgentState.ASKING);var next=interviewerSkill.stream(new QuestionInput(session.getCurrentTopic(),session.getCurrentDepth(),session.getJdSnapshot(),session.getResumeSnapshot(),history,decision.missingPoint()),session.getModel(),sink);transition(session,InterviewAgentState.WAITING_ANSWER);return new AgentTurnResult(decision.decision(),next,entity);}

 @Transactional public InterviewReport report(InterviewSession session){transition(session,InterviewAgentState.REPORTING);var evaluations=evaluationMapper.selectList(Wrappers.<InterviewEvaluation>lambdaQuery().eq(InterviewEvaluation::getSessionId,session.getId()).orderByAsc(InterviewEvaluation::getTurnNumber));var result=reportSkill.execute(evaluations);var report=new InterviewReport();report.setSessionId(session.getId());report.setScore(result.score());report.setTechnicalScore(result.technicalScore());report.setCommunicationScore(result.communicationScore());report.setCompletenessScore(result.completenessScore());report.setJdCoverage(result.jdCoverage());report.setStrength(result.strength());report.setWeakness(result.weakness());report.setSuggestion(result.suggestion());reportMapper.insert(report);memoryManager.rememberReport(session.getUserId(),result);session.setScore(result.score());session.setStatus(InterviewStatus.FINISHED);transition(session,InterviewAgentState.FINISHED);return report;}

 public List<InterviewEvaluation> evaluations(Long sessionId){return evaluationMapper.selectList(Wrappers.<InterviewEvaluation>lambdaQuery().eq(InterviewEvaluation::getSessionId,sessionId).orderByAsc(InterviewEvaluation::getTurnNumber));}
 private void transition(InterviewSession session,InterviewAgentState state){session.setAgentState(state);sessionMapper.updateById(session);}
 private String nextTopic(StrategyResult strategy,String current){var topics=strategy.topics();for(int i=0;i<topics.size();i++)if(topics.get(i).topic().equals(current))return i+1<topics.size()?topics.get(i+1).topic():null;return topics.get(0).topic();}
 @SuppressWarnings("unchecked") private void append(Map<String,Object> memory,String key,List<String> values){var list=new ArrayList<String>((List<String>)memory.getOrDefault(key,List.of()));list.addAll(values);memory.put(key,list.stream().distinct().toList());}
 public record AgentTurnResult(InterviewDecision decision,String nextQuestion,InterviewEvaluation evaluation){}
}
