package com.careeragent.service;
import com.careeragent.agent.llm.LLMAdapter;import com.careeragent.domain.entity.*;import com.careeragent.domain.enums.*;import com.careeragent.dto.*;import com.careeragent.interview.agent.InterviewAgentOrchestrator;import com.careeragent.mapper.*;import com.careeragent.security.CurrentUserProvider;import com.careeragent.vo.ResumeVersionVO;import java.util.*;import org.junit.jupiter.api.Test;import static org.assertj.core.api.Assertions.assertThat;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;
class InterviewServiceTests {
 @Test void createRunsPreparationWithSelectedResume(){
  var sessions=mock(InterviewSessionMapper.class);var messages=mock(InterviewMessageMapper.class);var user=mock(CurrentUserProvider.class);var versions=mock(ResumeVersionService.class);var agent=mock(InterviewAgentOrchestrator.class);
  when(user.getCurrentUserId()).thenReturn(1L);doAnswer(inv->{((InterviewSession)inv.getArgument(0)).setId(21L);return 1;}).when(sessions).insert(any(InterviewSession.class));
  var resume=new ResumeVersionVO();resume.setId(9L);resume.setContentMarkdown("React 项目");resume.setTargetJobName("前端开发");when(versions.get(9L)).thenReturn(resume);when(agent.prepare(any(),eq("前端开发"),eq(""),eq("React 项目"),any())).thenReturn("请介绍你的 React 项目");
  var result=service(sessions,messages,mock(InterviewReportMapper.class),user,versions,agent).create(new InterviewCreateRequest(null,null,9L,InterviewStage.TECH_ONE,InterviewMode.PROJECT_DEEP,30,"mock"));
  assertThat(result.sessionId()).isEqualTo(21L);assertThat(result.firstMessage().content()).contains("React");verify(agent).prepare(any(),anyString(),anyString(),anyString(),any());
 }
 @Test void replyDelegatesEvaluationAndDecisionToAgent(){
  var sessions=mock(InterviewSessionMapper.class);var messages=mock(InterviewMessageMapper.class);var agent=mock(InterviewAgentOrchestrator.class);var session=active();when(sessions.selectOne(any())).thenReturn(session);var question=message(1L,"assistant","介绍项目");when(messages.selectList(any())).thenReturn(List.of(question));doAnswer(inv->{var value=(InterviewMessage)inv.getArgument(0);if(value.getId()==null)value.setId(2L);return 1;}).when(messages).insert(any(InterviewMessage.class));when(agent.answer(any(),any(),any(),anyList(),any())).thenReturn(new InterviewAgentOrchestrator.AgentTurnResult(InterviewDecision.NEXT_TOPIC,"为什么选择 React？",new InterviewEvaluation()));
  var result=service(sessions,messages,mock(InterviewReportMapper.class),mock(CurrentUserProvider.class),mock(ResumeVersionService.class),agent).reply(21L,new InterviewMessageRequest("因为组件化","mock"));assertThat(result.content()).contains("React");verify(agent).answer(any(),eq(question),any(),anyList(),any());
 }
 @Test void finishUsesReportSkillResult(){var sessions=mock(InterviewSessionMapper.class);var reports=mock(InterviewReportMapper.class);var agent=mock(InterviewAgentOrchestrator.class);when(sessions.selectOne(any())).thenReturn(active());when(reports.selectOne(any())).thenReturn(null);var report=new InterviewReport();report.setScore(86);report.setTechnicalScore(88);report.setCommunicationScore(80);report.setCompletenessScore(82);report.setJdCoverage(80);report.setStrength("项目表达清晰");report.setWeakness("缺少量化");report.setSuggestion("补充数据");when(agent.report(any())).thenReturn(report);var result=service(sessions,mock(InterviewMessageMapper.class),reports,mock(CurrentUserProvider.class),mock(ResumeVersionService.class),agent).finish(21L);assertThat(result.score()).isEqualTo(86);assertThat(result.technicalScore()).isEqualTo(88);}
 private InterviewService service(InterviewSessionMapper sessions,InterviewMessageMapper messages,InterviewReportMapper reports,CurrentUserProvider user,ResumeVersionService versions,InterviewAgentOrchestrator agent){return new InterviewService(sessions,messages,reports,mock(ApplicationService.class),mock(JobDescriptionService.class),user,mock(LLMAdapter.class),versions,mock(ResumeService.class),agent);}
 private InterviewSession active(){var value=new InterviewSession();value.setId(21L);value.setUserId(1L);value.setStage(InterviewStage.TECH_ONE);value.setMode(InterviewMode.PROJECT_DEEP);value.setDuration(30);value.setStatus(InterviewStatus.IN_PROGRESS);value.setAgentState(InterviewAgentState.WAITING_ANSWER);value.setCurrentTurn(0);value.setCurrentDepth(1);value.setCurrentTopic("项目深挖");return value;}
 private InterviewMessage message(Long id,String role,String content){var value=new InterviewMessage();value.setId(id);value.setRole(role);value.setContent(content);return value;}
}
