package com.careeragent.service;
import com.careeragent.agent.llm.LLMAdapter;import com.careeragent.agent.structured.*;import com.careeragent.domain.entity.*;import com.careeragent.domain.enums.*;import com.careeragent.dto.*;import com.careeragent.mapper.*;import com.careeragent.security.CurrentUserProvider;import java.util.*;import org.junit.jupiter.api.Test;import org.mockito.ArgumentCaptor;import static org.assertj.core.api.Assertions.assertThat;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;
class InterviewServiceTests {
 @Test void createPersistsSessionAndFirstAssistantQuestion(){var sessions=mock(InterviewSessionMapper.class);var messages=mock(InterviewMessageMapper.class);var llm=mock(LLMAdapter.class);var user=mock(CurrentUserProvider.class);when(user.getCurrentUserId()).thenReturn(1L);doAnswer(inv->{((InterviewSession)inv.getArgument(0)).setId(21L);return 1;}).when(sessions).insert(any(InterviewSession.class));when(llm.structuredOutput(anyString(),any(),eq(InterviewTurnOutput.class),nullable(String.class))).thenReturn(new InterviewTurnOutput("请介绍一个真实项目。"));var service=service(sessions,messages,mock(InterviewReportMapper.class),user,llm);var result=service.create(new InterviewCreateRequest(null,InterviewStage.TECH_ONE,InterviewMode.PROJECT_DEEP,30,"mock-career-agent"));assertThat(result.sessionId()).isEqualTo(21L);assertThat(result.firstMessage().role()).isEqualTo("assistant");assertThat(result.firstMessage().content()).contains("真实项目");verify(sessions).insert(any(InterviewSession.class));verify(messages).insert(any(InterviewMessage.class));}
 @Test void replyPersistsUserAnswerThenAssistantFollowUp(){var sessions=mock(InterviewSessionMapper.class);var messages=mock(InterviewMessageMapper.class);var llm=mock(LLMAdapter.class);var session=active();when(sessions.selectOne(any())).thenReturn(session);var userMessage=new InterviewMessage();userMessage.setRole("user");userMessage.setContent("我负责工具调用模块");when(messages.selectList(any())).thenReturn(List.of(userMessage));when(llm.structuredOutput(anyString(),any(),eq(InterviewTurnOutput.class),nullable(String.class))).thenReturn(new InterviewTurnOutput("为什么选择这个方案？"));var service=service(sessions,messages,mock(InterviewReportMapper.class),mock(CurrentUserProvider.class),llm);var result=service.reply(21L,new InterviewMessageRequest("我负责工具调用模块","mock-career-agent"));assertThat(result.role()).isEqualTo("assistant");assertThat(result.content()).contains("为什么");var captor=ArgumentCaptor.forClass(InterviewMessage.class);verify(messages,times(2)).insert(captor.capture());assertThat(captor.getAllValues()).extracting(InterviewMessage::getRole).containsExactly("user","assistant");}
 @Test void finishPersistsReportAndMarksSessionFinished(){var sessions=mock(InterviewSessionMapper.class);var reports=mock(InterviewReportMapper.class);var llm=mock(LLMAdapter.class);var session=active();when(sessions.selectOne(any())).thenReturn(session);when(reports.selectOne(any())).thenReturn(null);when(llm.structuredOutput(anyString(),any(),eq(InterviewReportOutput.class),nullable(String.class))).thenReturn(new InterviewReportOutput(86,"项目表达清晰","缺少量化证据","补充结果证据"));var service=service(sessions,mock(InterviewMessageMapper.class),reports,mock(CurrentUserProvider.class),llm);var result=service.finish(21L);assertThat(result.score()).isEqualTo(86);assertThat(session.getStatus()).isEqualTo(InterviewStatus.FINISHED);assertThat(session.getScore()).isEqualTo(86);verify(reports).insert(any(InterviewReport.class));verify(sessions).updateById(session);}
 private InterviewService service(InterviewSessionMapper sessions,InterviewMessageMapper messages,InterviewReportMapper reports,CurrentUserProvider user,LLMAdapter llm){return new InterviewService(sessions,messages,reports,mock(ApplicationService.class),mock(JobDescriptionService.class),user,llm);}
 private InterviewSession active(){var value=new InterviewSession();value.setId(21L);value.setUserId(1L);value.setStage(InterviewStage.TECH_ONE);value.setMode(InterviewMode.PROJECT_DEEP);value.setDuration(30);value.setStatus(InterviewStatus.IN_PROGRESS);return value;}
}
