ALTER TABLE interview_session ADD COLUMN resume_version_id BIGINT REFERENCES resume_version(id) ON DELETE RESTRICT;
ALTER TABLE interview_session ADD COLUMN agent_state VARCHAR(30) NOT NULL DEFAULT 'INIT';
ALTER TABLE interview_session ADD COLUMN decision VARCHAR(20);
ALTER TABLE interview_session ADD COLUMN current_topic VARCHAR(200);
ALTER TABLE interview_session ADD COLUMN current_depth INTEGER NOT NULL DEFAULT 0;
ALTER TABLE interview_session ADD COLUMN current_turn INTEGER NOT NULL DEFAULT 0;
ALTER TABLE interview_session ADD COLUMN jd_snapshot TEXT;
ALTER TABLE interview_session ADD COLUMN resume_snapshot TEXT;
ALTER TABLE interview_session ADD COLUMN jd_analysis JSONB NOT NULL DEFAULT '{}';
ALTER TABLE interview_session ADD COLUMN resume_analysis JSONB NOT NULL DEFAULT '{}';
ALTER TABLE interview_session ADD COLUMN interview_strategy JSONB NOT NULL DEFAULT '{}';
ALTER TABLE interview_session ADD COLUMN session_memory JSONB NOT NULL DEFAULT '{}';
ALTER TABLE interview_message ADD COLUMN turn_number INTEGER;
ALTER TABLE interview_message ADD COLUMN topic VARCHAR(200);
ALTER TABLE interview_message ADD COLUMN question_level INTEGER;
ALTER TABLE interview_message ADD COLUMN message_status VARCHAR(20) NOT NULL DEFAULT 'COMPLETED';
ALTER TABLE interview_report ADD COLUMN technical_score INTEGER;
ALTER TABLE interview_report ADD COLUMN communication_score INTEGER;
ALTER TABLE interview_report ADD COLUMN completeness_score INTEGER;
ALTER TABLE interview_report ADD COLUMN jd_coverage INTEGER;
CREATE TABLE interview_evaluation(id BIGSERIAL PRIMARY KEY,session_id BIGINT NOT NULL REFERENCES interview_session(id) ON DELETE CASCADE,turn_number INTEGER NOT NULL,question_message_id BIGINT NOT NULL REFERENCES interview_message(id),answer_message_id BIGINT NOT NULL REFERENCES interview_message(id),topic VARCHAR(200),technical_correctness INTEGER NOT NULL,completeness INTEGER NOT NULL,communication INTEGER NOT NULL,overall_score INTEGER NOT NULL,strengths JSONB NOT NULL DEFAULT '[]',missing_points JSONB NOT NULL DEFAULT '[]',risk_points JSONB NOT NULL DEFAULT '[]',recommended_decision VARCHAR(20) NOT NULL,final_decision VARCHAR(20) NOT NULL,decision_reason TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(session_id,turn_number));
CREATE INDEX idx_interview_evaluation_session ON interview_evaluation(session_id,turn_number);
CREATE TABLE user_interview_memory(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL UNIQUE REFERENCES app_user(id) ON DELETE CASCADE,target_directions JSONB NOT NULL DEFAULT '[]',technical_skills JSONB NOT NULL DEFAULT '[]',recurring_strengths JSONB NOT NULL DEFAULT '[]',recurring_weaknesses JSONB NOT NULL DEFAULT '[]',created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
