ALTER TABLE resume ADD COLUMN source VARCHAR(20) NOT NULL DEFAULT 'CREATE';
ALTER TABLE resume ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'CONFIRMED';
ALTER TABLE resume ADD COLUMN basic_info JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE resume ADD COLUMN file_url VARCHAR(2000);
ALTER TABLE resume ADD COLUMN file_name VARCHAR(500);
ALTER TABLE resume ADD COLUMN file_type VARCHAR(100);

ALTER TABLE resume ADD CONSTRAINT ck_resume_source CHECK (source IN ('UPLOAD', 'CREATE'));
ALTER TABLE resume ADD CONSTRAINT ck_resume_status CHECK (status IN ('DRAFT', 'CONFIRMED'));
