import { useNavigate } from 'react-router-dom'
import { useAnalyzeJob, useJobDetail, useLatestJobMatch, useMatchResumeToJob } from '../../hooks/useJobRadar.js'
import JobMatchSummary from './JobMatchSummary.jsx'

const labels = { CAMPUS: '校招', INTERNSHIP: '实习', SOCIAL: '社招', MANUAL: '手动录入', OFFICIAL_SITE: '官方招聘网站', BYTEDANCE: '字节跳动官网', THIRD_PARTY: '招聘平台' }
export default function JobDetailPanel({ jobId, resume }) {
  const navigate = useNavigate(); const detail = useJobDetail(jobId); const match = useLatestJobMatch(jobId, resume?.id)
  const analyze = useAnalyzeJob(); const runMatch = useMatchResumeToJob(); const job = detail.data
  const analyzed = Boolean(job?.responsibilities?.length || job?.requiredSkills?.length || job?.keywords?.length)
  if (!jobId) return <aside className="sticky top-0 flex h-screen w-[350px] shrink-0 items-center justify-center border-l border-black/10 bg-[#f8f6f0] p-8 text-center text-sm leading-6 text-stone-400">选择一个岗位，查看结构化 JD、匹配证据与下一步建议。</aside>
  if (detail.isLoading) return <aside className="sticky top-0 h-screen w-[350px] shrink-0 animate-pulse border-l border-black/10 bg-[#f8f6f0] p-7"><div className="h-5 w-2/3 rounded bg-stone-200"/><div className="mt-3 h-8 rounded bg-stone-200"/></aside>
  if (detail.isError) return <aside className="sticky top-0 h-screen w-[350px] shrink-0 border-l border-black/10 bg-[#f8f6f0] p-7"><p className="text-sm text-red-700">岗位详情加载失败</p><button onClick={() => detail.refetch()} className="mt-3 text-xs underline">重新尝试</button></aside>
  const matchedEvidence = match.data?.evidence?.filter((item) => item.result === 'MATCHED').slice(0, 2) || []
  return <aside className="sticky top-0 h-screen w-[clamp(320px,27vw,380px)] shrink-0 overflow-y-auto border-l border-black/10 bg-[#f8f6f0] px-7 py-8"><div className="flex items-start justify-between"><div><p className="text-xs text-stone-400">{job.company}</p><h2 className="mt-2 text-2xl font-semibold leading-tight tracking-[-.025em]">{job.jobName}</h2></div><span className="rounded-full border border-black/10 px-2 py-1 text-[10px]">#{job.id}</span></div><div className="mt-5 grid grid-cols-2 gap-y-3 text-xs"><p><span className="block text-stone-400">城市</span><b className="mt-1 block font-medium">{job.city || '待确认'}</b></p><p><span className="block text-stone-400">招聘类型</span><b className="mt-1 block font-medium">{labels[job.recruitmentType] || job.recruitmentType}</b></p><p><span className="block text-stone-400">来源</span><b className="mt-1 block font-medium">{labels[job.source] || job.source}</b></p><p><span className="block text-stone-400">最近更新</span><b className="mt-1 block font-medium">{new Date(job.updatedAt).toLocaleDateString('zh-CN')}</b></p></div>{job.sourceUrl && <a href={job.sourceUrl} target="_blank" rel="noreferrer" className="mt-5 flex w-full items-center justify-between rounded-xl border border-black/10 bg-white/50 px-4 py-3 text-xs font-semibold hover:bg-white">打开招聘官网 <span>↗</span></a>}
    <details className="group mt-7 border-t border-black/10 pt-5"><summary className="flex cursor-pointer list-none items-center justify-between text-sm font-semibold"><span>完整岗位 JD</span><span className="text-xs font-normal text-stone-400 group-open:hidden">展开</span><span className="hidden text-xs font-normal text-stone-400 group-open:inline">收起</span></summary><div className="mt-4 max-h-[460px] overflow-y-auto rounded-xl bg-white/55 px-4 py-4"><p className="whitespace-pre-wrap text-xs leading-6 text-stone-700">{job.rawContent || '该岗位暂时没有原始 JD 内容。'}</p></div></details>
    <section className="mt-8 border-t border-black/10 pt-6"><p className="text-sm font-semibold">为什么推荐给你</p>{matchedEvidence.length ? <div className="mt-3 space-y-3">{matchedEvidence.map((item) => <p key={`${item.jobRequirement}-${item.resumeItemId}`} className="text-xs leading-5 text-stone-600">你的{item.resumeSection === 'PROJECT' ? '项目' : '简历'}中存在 <b className="text-stone-800">{item.resumeEvidence}</b>，与 JD 的“{item.jobRequirement}”直接对应。</p>)}</div> : <p className="mt-3 text-xs leading-5 text-stone-400">完成简历匹配后，这里会展示基于证据的推荐理由。</p>}</section>
    {!analyzed && <section className="mt-7 rounded-xl border border-[#d8d1c3] bg-[#fffcf5] p-4"><p className="text-sm font-semibold">该岗位尚未完成结构化分析</p><p className="mt-2 text-xs leading-5 text-stone-500">提取职责、技能与岗位侧重点后，才能得到更可靠的匹配参考。</p><button onClick={() => analyze.mutate(job.id)} disabled={analyze.isPending} className="mt-4 w-full rounded-lg bg-[#1b1b18] py-2.5 text-xs font-semibold text-white disabled:opacity-50">{analyze.isPending ? '正在解析岗位职责…' : analyze.isError ? '分析失败，重新尝试' : '分析 JD'}</button></section>}
    {analyzed && !match.data && <section className="mt-7 rounded-xl border border-[#cfdde2] bg-[#f2f7f8] p-4"><p className="text-sm font-semibold">尚未与默认简历匹配</p><p className="mt-2 text-xs leading-5 text-stone-500">{resume ? `将使用「${resume.name}」生成带证据的匹配报告。` : '暂无默认简历，请先设置一份默认简历。'}</p><button onClick={() => runMatch.mutate({ jobId: job.id, resumeId: resume.id })} disabled={!resume || runMatch.isPending} className="mt-4 w-full rounded-lg bg-[#1b1b18] py-2.5 text-xs font-semibold text-white disabled:opacity-40">{runMatch.isPending ? '正在匹配简历…' : runMatch.isError ? '匹配失败，重新尝试' : '开始匹配'}</button></section>}
    {match.isLoading && resume && <p className="mt-7 text-xs text-stone-400">正在读取最新匹配报告…</p>}<JobMatchSummary report={match.data}/>
    {analyzed && <section className="mt-7 border-t border-black/10 pt-5"><p className="text-xs font-semibold text-stone-500">岗位核心技能</p><div className="mt-2 flex flex-wrap gap-1.5">{job.requiredSkills?.slice(0, 8).map((item) => <span key={item} className="rounded-md bg-[#e6eef1] px-2 py-1 text-[11px] text-[#3f5e69]">{item}</span>)}</div></section>}
    <button onClick={() => navigate(`/resumes/customize?jobId=${job.id}`)} className="mt-8 w-full rounded-xl bg-[#191917] py-3.5 text-sm font-semibold text-white shadow-sm hover:bg-black">生成岗位专属简历 <span className="ml-1">→</span></button>
  </aside>
}
