import { useEffect, useState } from 'react'

export default function InterviewConfigPanel({applications=[],resumes=[],resumeVersions=[],onStart,pending,error,onHistory,defaultApplicationId=''}){
 const [form,setForm]=useState({applicationId:defaultApplicationId?String(defaultApplicationId):'',resumeSelection:'',stage:'TECH_ONE',mode:'FULL',duration:30})
 useEffect(()=>{if(!form.resumeSelection){const preferred=resumes.find(item=>item.isDefault)||resumes[0];const selection=preferred?`resume:${preferred.id}`:(resumeVersions[0]?`version:${resumeVersions[0].id}`:'');if(selection)setForm(value=>({...value,resumeSelection:selection}))}},[resumes,resumeVersions,form.resumeSelection])
 const change=key=>event=>setForm({...form,[key]:event.target.value})
 const submit=()=>{const [type,id]=form.resumeSelection.split(':');onStart({applicationId:form.applicationId?Number(form.applicationId):null,resumeId:type==='resume'?Number(id):null,resumeVersionId:type==='version'?Number(id):null,stage:form.stage,mode:form.mode,duration:Number(form.duration)})}
 return <div><PanelHeader eyebrow="New agent session" title="新建智能模拟面试"/><p className="mt-3 text-sm leading-6 text-stone-500">Agent 会先分析岗位 JD 和你选择的简历版本，再制定面试策略并进行递进追问。</p><div className="mt-7 space-y-5">
  <Field label="目标岗位（建议选择）"><select className="input" value={form.applicationId} onChange={change('applicationId')}><option value="">通用技术面试</option>{applications.map(item=><option key={item.id} value={item.id}>{item.company} · {item.jobName}</option>)}</select></Field>
  <Field label="本场使用的简历"><select className="input" value={form.resumeSelection} onChange={change('resumeSelection')}><option value="">请选择简历</option>{resumes.length>0&&<optgroup label="我的简历">{resumes.map(item=><option key={`resume-${item.id}`} value={`resume:${item.id}`}>{item.name||item.fileName||`简历 #${item.id}`}{item.isDefault?' · 默认':''}</option>)}</optgroup>}{resumeVersions.length>0&&<optgroup label="岗位定制版本">{resumeVersions.map(item=><option key={`version-${item.id}`} value={`version:${item.id}`}>{item.versionName||`简历版本 #${item.id}`} {item.targetJobName?`· ${item.targetJobName}`:''}</option>)}</optgroup>}</select>{!resumes.length&&!resumeVersions.length&&<p className="mt-2 text-xs text-red-700">请先在“我的简历”中新增或上传简历。</p>}</Field>
  <Field label="面试阶段"><select className="input" value={form.stage} onChange={change('stage')}><option value="HR">HR 面</option><option value="TECH_ONE">业务一面</option><option value="TECH_TWO">业务二面</option><option value="FINAL">终面</option></select></Field>
  <Field label="模拟模式"><select className="input" value={form.mode} onChange={change('mode')}><option value="FULL">完整模拟</option><option value="PROJECT_DEEP">项目深挖</option><option value="TECH_FOCUS">岗位专项</option><option value="PRESSURE">压力面</option></select></Field>
  <Field label="面试时长"><div className="grid grid-cols-3 gap-2">{[15,30,60].map(value=><button key={value} type="button" onClick={()=>setForm({...form,duration:value})} className={`rounded-xl border py-2.5 text-xs font-semibold ${form.duration===value?'border-black bg-black text-white':'border-black/10 bg-white/60'}`}>{value}分钟</button>)}</div></Field>
 </div>{error&&<p className="mt-5 text-sm text-red-700">创建失败：{error.message}</p>}<button disabled={pending||!form.resumeSelection} onClick={submit} className="mt-7 w-full rounded-xl bg-black py-3.5 text-sm font-semibold text-white disabled:opacity-40">{pending?'正在分析 JD、简历并制定策略…':'启动 Interview Agent'}</button><button onClick={onHistory} className="mt-3 w-full py-2 text-sm text-stone-500">查看历史模拟面试 →</button></div>
}
export function PanelHeader({eyebrow,title}){return <><p className="text-[10px] font-bold uppercase tracking-[.18em] text-stone-400">{eyebrow}</p><h2 className="mt-2 font-serif text-2xl">{title}</h2></>}
function Field({label,children}){return <label className="block"><span className="text-xs font-semibold text-stone-600">{label}</span><div className="mt-2">{children}</div></label>}
