import { useEffect, useRef, useState } from 'react'

export default function InterviewChat({ session, messages = [], loading, sending, onSend, onStop, pendingUser, streamingReply, model, modelOptions = [], onModelChange }) {
  const [content, setContent] = useState(''); const bottom = useRef()
  useEffect(() => { bottom.current?.scrollIntoView({ behavior: 'smooth' }) }, [messages, pendingUser, streamingReply])
  const submit = event => { event.preventDefault(); if (!content.trim() || sending) return; onSend(content.trim()); setContent('') }
  if (!session) return <main className="flex min-h-[calc(100vh-96px)] items-center justify-center"><div className="text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-[#e5ebe4] text-xl">✦</span><h1 className="mt-6 font-serif text-3xl">开始一次模拟面试</h1><p className="mt-3 text-sm text-stone-500">请在右侧配置目标岗位和面试模式</p></div></main>
  return <main className="flex h-screen min-w-0 flex-col">
    <header className="border-b border-black/10 px-8 py-5"><p className="text-xs text-stone-400">{session.company ? `${session.company} · ${session.job}` : '通用模拟面试'}</p><h1 className="mt-1 font-serif text-2xl">AI 模拟面试</h1></header>
    <div className="flex-1 overflow-y-auto px-8 py-8"><div className="mx-auto max-w-3xl space-y-7">{loading && <div className="h-24 animate-pulse rounded-2xl bg-black/5"/>}{messages.map(message => <Message key={message.id} message={message}/>)}{pendingUser && <Message message={{ role: 'user', content: pendingUser }}/>} {streamingReply && <Message message={{ role: 'assistant', content: streamingReply }}/>} {sending && !streamingReply && <div className="flex items-center gap-2 text-xs text-stone-400"><span className="h-2 w-2 animate-pulse rounded-full bg-stone-400"/>面试官正在整理追问…</div>}<div ref={bottom}/></div></div>
    <form onSubmit={submit} className="border-t border-black/10 bg-[#f5f2eb] p-5"><div className="mx-auto max-w-3xl rounded-2xl border border-black/10 bg-white/75 p-3 shadow-sm"><div className="flex items-center border-b border-black/[.07] px-2 pb-2"><span className="mr-2 text-[10px] font-bold uppercase tracking-[.14em] text-stone-400">模型</span><select disabled={sending || session.status === 'FINISHED'} value={model} onChange={event => onModelChange(event.target.value)} className="max-w-52 bg-transparent text-xs font-semibold outline-none disabled:opacity-50">{modelOptions.map(item => <option key={item} value={item}>{item}</option>)}</select><span className="ml-auto text-[10px] text-stone-400">下一次回复生效</span></div><div className="flex items-end gap-3 pt-2"><textarea rows="2" disabled={session.status === 'FINISHED' || sending} value={content} onChange={event => setContent(event.target.value)} onKeyDown={event => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); event.currentTarget.form.requestSubmit() } }} className="min-h-12 flex-1 resize-none bg-transparent px-2 py-2 text-sm outline-none disabled:opacity-50" placeholder={session.status === 'FINISHED' ? '本次面试已结束' : '输入你的回答，Enter 发送，Shift + Enter 换行'}/>{sending?<button type="button" onClick={()=>{setContent(pendingUser||'');onStop()}} className="rounded-xl border border-red-200 bg-red-50 px-5 py-3 text-sm font-semibold text-red-700">停止生成</button>:<button disabled={!content.trim() || session.status === 'FINISHED'} className="rounded-xl bg-black px-5 py-3 text-sm font-semibold text-white disabled:opacity-30">发送</button>}</div></div></form>
  </main>
}

function Message({ message }) { const assistant = message.role === 'assistant'; return <div className={`flex ${assistant ? 'justify-start' : 'justify-end'}`}><div className={`max-w-[82%] ${assistant ? '' : 'rounded-2xl bg-[#e4e1d8] px-5 py-3'}`}>{assistant && <p className="mb-2 text-[10px] font-bold uppercase tracking-[.15em] text-stone-400">AI 面试官</p>}<p className="whitespace-pre-wrap text-sm leading-7 text-stone-700">{message.content}</p></div></div> }
